#!/bin/sh
#
#Create a noninteractive `brew` external command by wrapping `brew-bu` (https://github.com/buo/homebrew-cask-upgrade)

#Use `brew-bu` to list all outdated formulas, but reject upgrading them if `brew-bu` wants interactive input, by feeding it a stream of "n"
yes n | brew bu "${@}"

if [ "${#}" = "0" ]
then
	#If no arguments were passed to `brew-bu`, clear the last line of the terminal, which contains the prompt for user input
	tput cr && tput el

	#Print a message explaining how to upgrade outdated casks in place of the interactive prompt
	echo 'If there are outdated formulas above, you can upgrade them by running `brew upgrade`'
fi
